### ISSUE TITLE
enable tests (when created)

### ISSUE THREAD

**Issue by github-actions[bot]** [battis/restful-api#34]
tests-and-coverage:

tests:

override:

https://github.com/battis/crud/blob/99d86a42741fbf22ffcecd9c090ba92c47a03bca/.scrutinizer.yml#L19

```yaml

            tests:
                override:
                    - php-scrutinizer-run
# TODO enable tests (when created)
#        tests-and-coverage:
#            tests:
#                override:

```
