### ISSUE TITLE
enable tests (when created)

### ISSUE THREAD

**Issue by github-actions[bot]** [battis/restful-api#35]
tests-and-coverage:

tests:

override:

https://github.com/battis/oauth2-server/blob/0cd862135350f726fb730a2914ea5ce5b06d521e/.scrutinizer.yml#L19

```yaml

            tests:
                override:
                    - php-scrutinizer-run
# TODO: enable tests (when created)
#        tests-and-coverage:
#            tests:
#                override:

```
