### ISSUE TITLE
enable tests (when created)

### ISSUE THREAD

**Issue by github-actions[bot]** [battis/restful-api#44]
tests-and-coverage:

tests:

override:

https://github.com/battis/user-session/blob/324537d962438bb2719ef34453bd755df1ed6890/.scrutinizer.yml#L19

```yaml

            tests:
                override:
                    - php-scrutinizer-run
# TODO enable tests (when created)
#        tests-and-coverage:
#            tests:
#                override:

```
